name: CI/CD Java Maven + Docker

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: self-hosted  # <- usa runner local

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Maven e Testes
        run: mvn clean install

      - name: Build Docker Image
        run: docker build -t meuapp-java:latest .

  deploy:
    needs: build-test
    runs-on: self-hosted  # <- usa runner local

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Deploy local com Docker
        run: |
          docker stop meuapp-java || true
          docker rm meuapp-java || true
          docker run -d --name meuapp-java -p 8080:8080 meuapp-java:latest
